## Task: Make a list of freelancers and their information in Canada on the freelancer website 
## Website: https://www.freelancer.com/freelancers/canada/python
## Skill: Webscraping

In [266]:
import urllib.request as req
from bs4 import BeautifulSoup
import pandas as pd 
from time import sleep 
from random import randint

In [268]:
url = "https://www.freelancer.com/freelancers/canada/python/1"
html = req.urlopen(url)
doc = BeautifulSoup(html, "html.parser")

In [269]:
name0= doc.find_all(class_="find-freelancer-username-mobile")
name0

[<a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/WebDevWang">
                         WebDevWang
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/tangramua">
                         tangramua
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/mixun0">
                         mixun0
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/pauldinhdev">
                         pauldinhdev
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/amirrmusavifr">
                         amirrmusavifr
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/alextoross09">
                         alextoross09
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/Tereus77">
                         Tereus77
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/anisbouk">
                         anisbouk
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/PentabayC">
                         PentabayC
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/jameso64">
                         jameso64
                     </a>]

In [272]:
len(doc.find_all(class_="find-freelancer-username-mobile"))

10

In [274]:
for n in name0:
    print(n.text)

                        WebDevWang


                        tangramua


                        mixun0


                        pauldinhdev


                        amirrmusavifr


                        alextoross09


                        Tereus77


                        anisbouk


                        PentabayC


                        jameso64

In [276]:
name1 = [n.text.strip() for n in name0]
name1

['WebDevWang',
 'tangramua',
 'mixun0',
 'pauldinhdev',
 'amirrmusavifr',
 'alextoross09',
 'Tereus77',
 'anisbouk',
 'PentabayC',
 'jameso64']

In [278]:
review0=doc.find_all(class_="Rating Rating--labeled")
review0

[<span class="Rating Rating--labeled" data-star_rating="4.8">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="4.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="5.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="5.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="4.8">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="5.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="5.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="5.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="5.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>]

In [280]:
review1 = [r["data-star_rating"] for r in review0]
review1

['4.8', '4.0', '5.0', '5.0', '4.8', '5.0', '5.0', '5.0', '5.0', '0.0']

In [282]:
earning0= doc.find_all(class_= "Earnings-label freelancer-user-earnings")
earning0

[<span class="Earnings-label freelancer-user-earnings">
                         3.8
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         7.2
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         3.2
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         4.4
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         4.8
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         4.1
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         2.5
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         1.8
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         1.8
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>]

In [284]:
for e in earning0:
    print(e.text)

                        3.8


                        7.2


                        3.2


                        4.4


                        4.8


                        4.1


                        2.5


                        1.8


                        1.8


                        0.0

In [286]:
earning1= [e.text.strip() for e in earning0]
earning1

['3.8', '7.2', '3.2', '4.4', '4.8', '4.1', '2.5', '1.8', '1.8', '0.0']

In [288]:
number0 = doc.find_all(class_="directory-freelancer-rating")
number0

[<a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/WebDevWang" target="_blank">
                         4 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/tangramua" target="_blank">
                         38 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/mixun0" target="_blank">
                         3 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/pauldinhdev" target="_blank">
                         6 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/amirrmusavifr" target="_blank">
                         12 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/alextoross09" target="_blank">
                         16 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/Tereus77" target="_blank">
                         1 review
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/anisbouk" target="_blank">
                         2 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/PentabayC" target="_blank">
                         2 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/jameso64" target="_blank">
                         0 reviews
                     </a>]

In [290]:
for l in number0:
   print(l.text)

                        4 reviews


                        38 reviews


                        3 reviews


                        6 reviews


                        12 reviews


                        16 reviews


                        1 review


                        2 reviews


                        2 reviews


                        0 reviews

In [292]:
number1=[l.text.strip() for l in number0]
number1

['4 reviews',
 '38 reviews',
 '3 reviews',
 '6 reviews',
 '12 reviews',
 '16 reviews',
 '1 review',
 '2 reviews',
 '2 reviews',
 '0 reviews']

In [294]:
len(number1)

10

In [296]:
rate0 =doc.find_all(class_="user-hourly-rate freelancer-hourlyrate")
rate0

[<span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="50" freelancer-hourlyrate="">$50 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="35" freelancer-hourlyrate="">$35 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="70" freelancer-hourlyrate="">$70 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="70" freelancer-hourlyrate="">$70 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="40" freelancer-hourlyrate="">$40 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="35" freelancer-hourlyrate="">$35 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="40" freelancer-hourlyrate="">$40 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="35" freelancer-hourlyrate="">$35 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>]

In [298]:
for r in rate0:
    print(r.text)

$50 USD per hour
$35 USD per hour
$70 USD per hour
$70 USD per hour
$20 USD per hour
$40 USD per hour
$35 USD per hour
$40 USD per hour
$35 USD per hour
$20 USD per hour

In [300]:
rate1=[r.text for r in rate0]
rate1

['$50 USD per hour',
 '$35 USD per hour',
 '$70 USD per hour',
 '$70 USD per hour',
 '$20 USD per hour',
 '$40 USD per hour',
 '$35 USD per hour',
 '$40 USD per hour',
 '$35 USD per hour',
 '$20 USD per hour']

In [302]:
len(rate1)

10

In [304]:
profile0=doc.find_all(class_="bio truncProfile")
profile0

[<div class="bio truncProfile"><span class="profile_text">⚡️ With 5 years of experience as a Full Stack Developer, I specialize in building web and mobile applications. My expertise includes Laravel, React, Vue, and various modern technologies. I am skilled in JavaScript, React Native, PHP, and API development, with a strong track record of delivering high-quality projects....</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">We are Canadian-Ukrainian team of highly professional software developers and system administrators with more than 20 years expertise.

 OUR MAIN SPECIALIZATIONS:

 1) WEB DEVELOPMENT &amp; SOFTWARE DEVELOPMENT

    1.1) FRONT-END: HTML, HTML5, CSS3, Bootstrap, TailwindCSS

    1.2) JAVASCRIPT:  JavaScript, ES6+, Typescript,...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I have experience in building websites and mobile apps for medium and big sized businesses in company for 10+ years.

 - Shopify,  Squarespace, Ruby on Rails,  PHP, React.JS, Angular, ASP.NET, VueJS, ColdFusion
 - Make.com, n8n.io, Zapier
 - C#, Python, Crawling/Scraping, APEX,
 - CI/CD, Salesforce, Heroku, AWS,...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">With over 10 years of experience in the IT industry, I am confident in my ability to make your project a resounding success. Holding a B.S. degree in computer science and numerous successful projects under my belt, I am well-equipped to meet your needs.

 Services I Offer:
 ⭐️ Web Development
 ⭐️ Mobile Development
 ⭐️...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I have master in Electrical Engineering, I'm expert with following skills:

 DIGITAL SIGNAL PROCESSING     (MATLAB &amp; PYTHON)
 * Estimation / Detection
 * Digital Communication Systems
 * Mathematics
 * Kalman Filter
 * Tracking System

 IMAGE PROCESSING      (MATLAB &amp; PYTHON)
 * Digital Image Processing
 * Image Classification...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I am a highly skilled Data Scientist and Software Engineer with extensive experience in Python, web scraping, and large language models (LLMs). I specialize in building robust REST APIs using FastAPI, developing machine learning and deep learning solutions, and creating insightful business intelligence dashboards. My...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">My name is William and I am an experienced AI &amp; Full Stack developer based in Canada.
 With 7 years of experience in software development, I have been working with AI technologies on Computer Vision area especially Video bots, LipSync, Text-to-Image models.
 Also have extensive experience in LLMs such as GPT, Gemini,...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I am a Senior Software Engineer with over 10 years of experience in developing robust, scalable applications.
 My expertise includes front-end development using React and Next.js, crafting dynamic user interfaces.
 I excel in back-end development with Node.js,  Laravel, Go and Python, creating efficient,...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Most Reviewed Companies by The Manifest in the Software Development category.
 Our team consists of seasoned professionals with a wealth of expertise, offering a diverse range of digital services to elevate your business:

 ✅ Custom Logo Design to establish a unique brand identity.
 ✅ Creative Graphics Design to...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">As a verified top-rated Upwork Full-Stack Solution Provider, I am your most trusted partner in amplifying your business's digital presence and growth. My extensive experience in various technologies positions me perfectly to deliver high-quality, custom solutions tailored to your specific needs. Here's a snapshot of...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>]

In [306]:
len(profile0)

10

In [308]:
for p in profile0:
    print(p.text)

⚡️ With 5 years of experience as a Full Stack Developer, I specialize in building web and mobile applications. My expertise includes Laravel, React, Vue, and various modern technologies. I am skilled in JavaScript, React Native, PHP, and API development, with a strong track record of delivering high-quality projects.... more
We are Canadian-Ukrainian team of highly professional software developers and system administrators with more than 20 years expertise.

OUR MAIN SPECIALIZATIONS:

1) WEB DEVELOPMENT & SOFTWARE DEVELOPMENT

   1.1) FRONT-END: HTML, HTML5, CSS3, Bootstrap, TailwindCSS

   1.2) JAVASCRIPT:  JavaScript, ES6+, Typescript,... more
I have experience in building websites and mobile apps for medium and big sized businesses in company for 10+ years.

- Shopify,  Squarespace, Ruby on Rails,  PHP, React.JS, Angular, ASP.NET, VueJS, ColdFusion
- Make.com, n8n.io, Zapier
- C#, Python, Crawling/Scraping, APEX,
- CI/CD, Salesforce, Heroku, AWS,... more
With over 10 years of experience in the IT industry, I am confident in my ability to make your project a resounding success. Holding a B.S. degree in computer science and numerous successful projects under my belt, I am well-equipped to meet your needs.

Services I Offer:
⭐️ Web Development
⭐️ Mobile Development
⭐️... more
I have master in Electrical Engineering, I'm expert with following skills:

DIGITAL SIGNAL PROCESSING     (MATLAB & PYTHON)
* Estimation / Detection
* Digital Communication Systems
* Mathematics
* Kalman Filter
* Tracking System

IMAGE PROCESSING      (MATLAB & PYTHON)
* Digital Image Processing
* Image Classification... more
I am a highly skilled Data Scientist and Software Engineer with extensive experience in Python, web scraping, and large language models (LLMs). I specialize in building robust REST APIs using FastAPI, developing machine learning and deep learning solutions, and creating insightful business intelligence dashboards. My... more
My name is William and I am an experienced AI & Full Stack developer based in Canada.
With 7 years of experience in software development, I have been working with AI technologies on Computer Vision area especially Video bots, LipSync, Text-to-Image models.
Also have extensive experience in LLMs such as GPT, Gemini,... more
I am a Senior Software Engineer with over 10 years of experience in developing robust, scalable applications.
My expertise includes front-end development using React and Next.js, crafting dynamic user interfaces.
I excel in back-end development with Node.js,  Laravel, Go and Python, creating efficient,... more
Most Reviewed Companies by The Manifest in the Software Development category.
Our team consists of seasoned professionals with a wealth of expertise, offering a diverse range of digital services to elevate your business:

✅ Custom Logo Design to establish a unique brand identity.
✅ Creative Graphics Design to... more
As a verified top-rated Upwork Full-Stack Solution Provider, I am your most trusted partner in amplifying your business's digital presence and growth. My extensive experience in various technologies positions me perfectly to deliver high-quality, custom solutions tailored to your specific needs. Here's a snapshot of... more

In [310]:
profile1 = [p.text for p in profile0]
profile1

['⚡️ With 5 years of experience as a Full Stack Developer, I specialize in building web and mobile applications. My expertise includes Laravel, React, Vue, and various modern technologies. I am skilled in JavaScript, React Native, PHP, and API development, with a strong track record of delivering high-quality projects.... more',
 'We are Canadian-Ukrainian team of highly professional software developers and system administrators with more than 20 years expertise. \n\nOUR MAIN SPECIALIZATIONS:\n\n1) WEB DEVELOPMENT & SOFTWARE DEVELOPMENT\n\n   1.1) FRONT-END: HTML, HTML5, CSS3, Bootstrap, TailwindCSS\n\n   1.2) JAVASCRIPT:  JavaScript, ES6+, Typescript,... more',
 'I have experience in building websites and mobile apps for medium and big sized businesses in company for 10+ years.\n\n- Shopify,  Squarespace, Ruby on Rails,  PHP, React.JS, Angular, ASP.NET, VueJS, ColdFusion\n- Make.com, n8n.io, Zapier\n- C#, Python, Crawling/Scraping, APEX, \n- CI/CD, Salesforce, Heroku, AWS,... more',
 'With over 10 years of experience in the IT industry, I am confident in my ability to make your project a resounding success. Holding a B.S. degree in computer science and numerous successful projects under my belt, I am well-equipped to meet your needs.\n\nServices I Offer:\n⭐️ Web Development\n⭐️ Mobile Development\n⭐️... more',
 "I have master in Electrical Engineering, I'm expert with following skills:\n\nDIGITAL SIGNAL PROCESSING     (MATLAB & PYTHON)\n* Estimation / Detection\n* Digital Communication Systems\n* Mathematics\n* Kalman Filter\n* Tracking System\n\nIMAGE PROCESSING      (MATLAB & PYTHON)\n* Digital Image Processing\n* Image Classification... more",
 'I am a highly skilled Data Scientist and Software Engineer with extensive experience in Python, web scraping, and large language models (LLMs). I specialize in building robust REST APIs using FastAPI, developing machine learning and deep learning solutions, and creating insightful business intelligence dashboards. My... more',
 'My name is William and I am an experienced AI & Full Stack developer based in Canada.\nWith 7 years of experience in software development, I have been working with AI technologies on Computer Vision area especially Video bots, LipSync, Text-to-Image models.\nAlso have extensive experience in LLMs such as GPT, Gemini,... more',
 'I am a Senior Software Engineer with over 10 years of experience in developing robust, scalable applications. \nMy expertise includes front-end development using React and Next.js, crafting dynamic user interfaces. \nI excel in back-end development with Node.js,  Laravel, Go and Python, creating efficient,... more',
 'Most Reviewed Companies by The Manifest in the Software Development category.\nOur team consists of seasoned professionals with a wealth of expertise, offering a diverse range of digital services to elevate your business:\n\n✅ Custom Logo Design to establish a unique brand identity.\n✅ Creative Graphics Design to... more',
 "As a verified top-rated Upwork Full-Stack Solution Provider, I am your most trusted partner in amplifying your business's digital presence and growth. My extensive experience in various technologies positions me perfectly to deliver high-quality, custom solutions tailored to your specific needs. Here's a snapshot of... more"]

In [312]:
len(profile1)

10

In [314]:
table1=pd.DataFrame({"Name": name1, "Review score": review1, "Earning": earning1, "# of reviews": number1, "Rate": rate1, "Profile": profile1})
table1

,Name,Review score,Earning,# of reviews,Rate,Profile
0,WebDevWang,4.8,3.8,4 reviews,$50 USD per hour,⚡️ With 5 years of experience as a Full Stack ...
1,tangramua,4.0,7.2,38 reviews,$35 USD per hour,We are Canadian-Ukrainian team of highly profe...
2,mixun0,5.0,3.2,3 reviews,$70 USD per hour,I have experience in building websites and mob...
3,pauldinhdev,5.0,4.4,6 reviews,$70 USD per hour,With over 10 years of experience in the IT ind...
4,amirrmusavifr,4.8,4.8,12 reviews,$20 USD per hour,"I have master in Electrical Engineering, I'm e..."
5,alextoross09,5.0,4.1,16 reviews,$40 USD per hour,I am a highly skilled Data Scientist and Softw...
6,Tereus77,5.0,2.5,1 review,$35 USD per hour,My name is William and I am an experienced AI ...
7,anisbouk,5.0,1.8,2 reviews,$40 USD per hour,I am a Senior Software Engineer with over 10 y...
8,PentabayC,5.0,1.8,2 reviews,$35 USD per hour,Most Reviewed Companies by The Manifest in the...
9,jameso64,0.0,0.0,0 reviews,$20 USD per hour,As a verified top-rated Upwork Full-Stack Solu...

In [316]:
url = "https://www.freelancer.com/freelancers/canada/python/2"
html = req.urlopen(url)
doc = BeautifulSoup(html, "html.parser")

In [318]:
name0= doc.find_all(class_="find-freelancer-username-mobile")
name0

[<a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/Time2Sync">
                         Time2Sync
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/tonyc00">
                         tonyc00
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/jameso64">
                         jameso64
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/juliann36">
                         juliann36
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/dilshodd1">
                         dilshodd1
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/daniell162">
                         daniell162
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/markw096">
                         markw096
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/martinm034">
                         martinm034
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/nuhumalik">
                         nuhumalik
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/jamess219">
                         jamess219
                     </a>]

In [320]:
for n in name0:
    print(n.text)

                        Time2Sync


                        tonyc00


                        jameso64


                        juliann36


                        dilshodd1


                        daniell162


                        markw096


                        martinm034


                        nuhumalik


                        jamess219

In [322]:
name2 = [n.text.strip() for n in name0]
name2

['Time2Sync',
 'tonyc00',
 'jameso64',
 'juliann36',
 'dilshodd1',
 'daniell162',
 'markw096',
 'martinm034',
 'nuhumalik',
 'jamess219']

In [324]:
review0=doc.find_all(class_="Rating Rating--labeled")
review0

[<span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>]

In [326]:
review2 = [r["data-star_rating"] for r in review0]
review2

['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0']

In [328]:
earning0= doc.find_all(class_= "Earnings-label freelancer-user-earnings")
earning0

[<span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>]

In [330]:
for e in earning0:
    print(e.text)

                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0

In [332]:
earning2= [e.text.strip() for e in earning0]
earning2

['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0']

In [334]:
number0 = doc.find_all(class_="directory-freelancer-rating")
number0

[<a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/Time2Sync" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/tonyc00" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/jameso64" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/juliann36" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/dilshodd1" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/daniell162" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/markw096" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/martinm034" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/nuhumalik" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/jamess219" target="_blank">
                         0 reviews
                     </a>]

In [336]:
for l in number0:
   print(l.text)

                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews

In [338]:
number2=[l.text.strip() for l in number0]
number2

['0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews']

In [340]:
rate0 =doc.find_all(class_="user-hourly-rate freelancer-hourlyrate")
rate0

[<span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="30" freelancer-hourlyrate="">$30 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="50" freelancer-hourlyrate="">$50 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="15" freelancer-hourlyrate="">$15 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="40" freelancer-hourlyrate="">$40 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="15" freelancer-hourlyrate="">$15 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="40" freelancer-hourlyrate="">$40 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="30" freelancer-hourlyrate="">$30 USD per hour</span>]

In [342]:
for r in rate0:
    print(r.text)

$30 USD per hour
$50 USD per hour
$20 USD per hour
$15 USD per hour
$40 USD per hour
$15 USD per hour
$20 USD per hour
$20 USD per hour
$40 USD per hour
$30 USD per hour

In [344]:
rate2=[r.text for r in rate0]
rate2

['$30 USD per hour',
 '$50 USD per hour',
 '$20 USD per hour',
 '$15 USD per hour',
 '$40 USD per hour',
 '$15 USD per hour',
 '$20 USD per hour',
 '$20 USD per hour',
 '$40 USD per hour',
 '$30 USD per hour']

In [346]:
profile0=doc.find_all(class_="bio truncProfile")
profile0

[<div class="bio truncProfile"><span class="profile_text">Welcome to Time2sync, your go-to partner for innovative technology solutions. Our dedicated team of experts excels in a variety of technologies, including ASP.net, C#, Linux servers, MSSQL, MySQL, HTML, PHP, and full-stack development. With a proven track record, we have successfully extended our capabilities to...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Hi, I’m a Data Scientist and AI/ML Engineer with a deep passion for AI, NLP, and Recommender Systems. With over 5 years of experience, I’ve worked on everything from Generative AI to business analytics and automation, helping organizations turn complex data into meaningful, actionable insights.

 I love building...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">As a verified top-rated Upwork Full-Stack Solution Provider, I am your most trusted partner in amplifying your business's digital presence and growth. My extensive experience in various technologies positions me perfectly to deliver high-quality, custom solutions tailored to your specific needs. Here's a snapshot of...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">With over 6 years of experience in full-stack development, I specialize in building dynamic, high-performing web applications and mobile solutions. My expertise lies in React, Node.js, AWS, and Django, making me an ideal candidate for building complex systems that require a combination of front-end and back-end...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Hello! My name is Dilshod, and I specialize in Algorithmic Trading, Trading Bot Development, Financial Analysis and Web App Development. With expertise in Pine Script and a deep understanding of market dynamics, I’ve built and optimized automated trading systems that deliver consistent results.

 What I Offer:
 •	Pine...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I am a highly skilled Full-Stack Developer with extensive experience in AI, blockchain, and WebRTC technologies, offering innovative, scalable, and efficient web development solutions. With 8+ years of expertise in designing, building, and maintaining high-performance web applications, I specialize in both front-end...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Hello! I am a dedicated AI and Image Processing expert with over 8 years of hands-on experience in Object Detection, Tracking, and Robotics. I specialize in:

 ✅ Computer Vision &amp; Image Processing (OpenCV, PIL, Scikit-Image)
 ✅ Deep Learning &amp; AI (YOLO, TensorFlow, PyTorch, OpenAI)
 ✅ Object Detection &amp; Tracking...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">As a skilled Full-Stack Developer with a deep focus on AI, blockchain, and WebRTC technologies, I bring over 8+ years of extensive experience in delivering high-performance, scalable, and innovative web solutions. I specialize in designing and implementing end-to-end solutions, from backend architecture to intuitive...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Hello.

 This is a versatile fullstack developer with 10+ years of proven experience and strong skills in web and mobile development.
 The reason I am confident that I can provide the perfect result is that I have worked on several projects using required technologies and they were very successful.
 Please check...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I am a Sr. full stack developer with extensive experience in developing modern application using React js, Node.js, Next.js, Python, and Django. From strategy to design to implementation, I take care of all possible product development stages. I can evaluate your application and propose improvements in any aspect of...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>]

In [348]:
for p in profile0:
    print(p.text)

Welcome to Time2sync, your go-to partner for innovative technology solutions. Our dedicated team of experts excels in a variety of technologies, including ASP.net, C#, Linux servers, MSSQL, MySQL, HTML, PHP, and full-stack development. With a proven track record, we have successfully extended our capabilities to... more
Hi, I’m a Data Scientist and AI/ML Engineer with a deep passion for AI, NLP, and Recommender Systems. With over 5 years of experience, I’ve worked on everything from Generative AI to business analytics and automation, helping organizations turn complex data into meaningful, actionable insights.

I love building... more
As a verified top-rated Upwork Full-Stack Solution Provider, I am your most trusted partner in amplifying your business's digital presence and growth. My extensive experience in various technologies positions me perfectly to deliver high-quality, custom solutions tailored to your specific needs. Here's a snapshot of... more
With over 6 years of experience in full-stack development, I specialize in building dynamic, high-performing web applications and mobile solutions. My expertise lies in React, Node.js, AWS, and Django, making me an ideal candidate for building complex systems that require a combination of front-end and back-end... more
Hello! My name is Dilshod, and I specialize in Algorithmic Trading, Trading Bot Development, Financial Analysis and Web App Development. With expertise in Pine Script and a deep understanding of market dynamics, I’ve built and optimized automated trading systems that deliver consistent results.

What I Offer:
•	Pine... more
I am a highly skilled Full-Stack Developer with extensive experience in AI, blockchain, and WebRTC technologies, offering innovative, scalable, and efficient web development solutions. With 8+ years of expertise in designing, building, and maintaining high-performance web applications, I specialize in both front-end... more
Hello! I am a dedicated AI and Image Processing expert with over 8 years of hands-on experience in Object Detection, Tracking, and Robotics. I specialize in:

✅ Computer Vision & Image Processing (OpenCV, PIL, Scikit-Image)
✅ Deep Learning & AI (YOLO, TensorFlow, PyTorch, OpenAI)
✅ Object Detection & Tracking... more
As a skilled Full-Stack Developer with a deep focus on AI, blockchain, and WebRTC technologies, I bring over 8+ years of extensive experience in delivering high-performance, scalable, and innovative web solutions. I specialize in designing and implementing end-to-end solutions, from backend architecture to intuitive... more
Hello.

This is a versatile fullstack developer with 10+ years of proven experience and strong skills in web and mobile development.
The reason I am confident that I can provide the perfect result is that I have worked on several projects using required technologies and they were very successful.
Please check... more
I am a Sr. full stack developer with extensive experience in developing modern application using React js, Node.js, Next.js, Python, and Django. From strategy to design to implementation, I take care of all possible product development stages. I can evaluate your application and propose improvements in any aspect of... more

In [350]:
profile2 = [p.text for p in profile0]
profile2

['Welcome to Time2sync, your go-to partner for innovative technology solutions. Our dedicated team of experts excels in a variety of technologies, including ASP.net, C#, Linux servers, MSSQL, MySQL, HTML, PHP, and full-stack development. With a proven track record, we have successfully extended our capabilities to... more',
 'Hi, I’m a Data Scientist and AI/ML Engineer with a deep passion for AI, NLP, and Recommender Systems. With over 5 years of experience, I’ve worked on everything from Generative AI to business analytics and automation, helping organizations turn complex data into meaningful, actionable insights.\n\nI love building... more',
 "As a verified top-rated Upwork Full-Stack Solution Provider, I am your most trusted partner in amplifying your business's digital presence and growth. My extensive experience in various technologies positions me perfectly to deliver high-quality, custom solutions tailored to your specific needs. Here's a snapshot of... more",
 'With over 6 years of experience in full-stack development, I specialize in building dynamic, high-performing web applications and mobile solutions. My expertise lies in React, Node.js, AWS, and Django, making me an ideal candidate for building complex systems that require a combination of front-end and back-end... more',
 'Hello! My name is Dilshod, and I specialize in Algorithmic Trading, Trading Bot Development, Financial Analysis and Web App Development. With expertise in Pine Script and a deep understanding of market dynamics, I’ve built and optimized automated trading systems that deliver consistent results.\n\nWhat I Offer:\n•\tPine... more',
 'I am a highly skilled Full-Stack Developer with extensive experience in AI, blockchain, and WebRTC technologies, offering innovative, scalable, and efficient web development solutions. With 8+ years of expertise in designing, building, and maintaining high-performance web applications, I specialize in both front-end... more',
 'Hello! I am a dedicated AI and Image Processing expert with over 8 years of hands-on experience in Object Detection, Tracking, and Robotics. I specialize in:\n\n✅ Computer Vision & Image Processing (OpenCV, PIL, Scikit-Image)\n✅ Deep Learning & AI (YOLO, TensorFlow, PyTorch, OpenAI)\n✅ Object Detection & Tracking... more',
 'As a skilled Full-Stack Developer with a deep focus on AI, blockchain, and WebRTC technologies, I bring over 8+ years of extensive experience in delivering high-performance, scalable, and innovative web solutions. I specialize in designing and implementing end-to-end solutions, from backend architecture to intuitive... more',
 'Hello.\n\nThis is a versatile fullstack developer with 10+ years of proven experience and strong skills in web and mobile development. \nThe reason I am confident that I can provide the perfect result is that I have worked on several projects using required technologies and they were very successful.\nPlease check... more',
 'I am a Sr. full stack developer with extensive experience in developing modern application using React js, Node.js, Next.js, Python, and Django. From strategy to design to implementation, I take care of all possible product development stages. I can evaluate your application and propose improvements in any aspect of... more']

In [352]:
table2=pd.DataFrame({"Name": name2, "Review score": review2, "Earning": earning2, "# of reviews": number2, "Rate": rate2, "Profile": profile2})
table2

,Name,Review score,Earning,# of reviews,Rate,Profile
0,Time2Sync,0.0,0.0,0 reviews,$30 USD per hour,"Welcome to Time2sync, your go-to partner for i..."
1,tonyc00,0.0,0.0,0 reviews,$50 USD per hour,"Hi, I’m a Data Scientist and AI/ML Engineer wi..."
2,jameso64,0.0,0.0,0 reviews,$20 USD per hour,As a verified top-rated Upwork Full-Stack Solu...
3,juliann36,0.0,0.0,0 reviews,$15 USD per hour,With over 6 years of experience in full-stack ...
4,dilshodd1,0.0,0.0,0 reviews,$40 USD per hour,"Hello! My name is Dilshod, and I specialize in..."
5,daniell162,0.0,0.0,0 reviews,$15 USD per hour,I am a highly skilled Full-Stack Developer wit...
6,markw096,0.0,0.0,0 reviews,$20 USD per hour,Hello! I am a dedicated AI and Image Processin...
7,martinm034,0.0,0.0,0 reviews,$20 USD per hour,As a skilled Full-Stack Developer with a deep ...
8,nuhumalik,0.0,0.0,0 reviews,$40 USD per hour,Hello.\n\nThis is a versatile fullstack develo...
9,jamess219,0.0,0.0,0 reviews,$30 USD per hour,I am a Sr. full stack developer with extensive...

In [354]:
url = "https://www.freelancer.com/freelancers/canada/python/3"
html = req.urlopen(url)
doc = BeautifulSoup(html, "html.parser")

In [356]:
name0= doc.find_all(class_="find-freelancer-username-mobile")
name0

[<a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/vnzabbar">
                         vnzabbar
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/darcyk1">
                         darcyk1
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/GulzarF">
                         GulzarF
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/henrym09">
                         henrym09
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/cyavash">
                         cyavash
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/shrawanm">
                         shrawanm
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/averyc7">
                         averyc7
                     </a>,
 <a class="find-freelancer-username-mobile" hireme-event="ProfileRedirect" hireme-label="Username" hireme-source="DirectoryPage" href="/u/shelinakhoja2">
                         shelinakhoja2
                     </a>]

In [358]:
for n in name0:
    print(n.text)

                        vnzabbar


                        darcyk1


                        GulzarF


                        henrym09


                        cyavash


                        shrawanm


                        averyc7


                        shelinakhoja2

In [360]:
name3 = [n.text.strip() for n in name0]
name3

['vnzabbar',
 'darcyk1',
 'GulzarF',
 'henrym09',
 'cyavash',
 'shrawanm',
 'averyc7',
 'shelinakhoja2']

In [362]:
review0=doc.find_all(class_="Rating Rating--labeled")
review0

[<span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>,
 <span class="Rating Rating--labeled" data-star_rating="0.0">
 <span class="Rating-total">
 <span class="Rating-progress"></span>
 </span>
 </span>]

In [364]:
review3 = [r["data-star_rating"] for r in review0]
review3

['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0']

In [366]:
earning0= doc.find_all(class_= "Earnings-label freelancer-user-earnings")
earning0

[<span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>,
 <span class="Earnings-label freelancer-user-earnings">
                         0.0
                     </span>]

In [368]:
for e in earning0:
    print(e.text)

                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0


                        0.0

In [370]:
earning3= [e.text.strip() for e in earning0]
earning3

['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0']

In [372]:
number0 = doc.find_all(class_="directory-freelancer-rating")
number0

[<a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/vnzabbar" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/darcyk1" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/GulzarF" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/henrym09" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/cyavash" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/shrawanm" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/averyc7" target="_blank">
                         0 reviews
                     </a>,
 <a class="directory-freelancer-rating" hireme-event="ProfileRedirect" hireme-label="ProfileReviews" hireme-source="DirectoryPage" href="/u/shelinakhoja2" target="_blank">
                         0 reviews
                     </a>]

In [374]:
for l in number0:
   print(l.text)

                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews


                        0 reviews

In [376]:
number3=[l.text.strip() for l in number0]
number3

['0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews',
 '0 reviews']

In [378]:
rate0 =doc.find_all(class_="user-hourly-rate freelancer-hourlyrate")
rate0

[<span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="45" freelancer-hourlyrate="">$45 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="35" freelancer-hourlyrate="">$35 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="15" freelancer-hourlyrate="">$15 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="50" freelancer-hourlyrate="">$50 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="20" freelancer-hourlyrate="">$20 USD per hour</span>,
 <span class="user-hourly-rate freelancer-hourlyrate" data-hourlyrate="30" freelancer-hourlyrate="">$30 USD per hour</span>]

In [380]:
for r in rate0:
    print(r.text)

$45 USD per hour
$20 USD per hour
$35 USD per hour
$15 USD per hour
$20 USD per hour
$50 USD per hour
$20 USD per hour
$30 USD per hour

In [382]:
rate3=[r.text for r in rate0]
rate3

['$45 USD per hour',
 '$20 USD per hour',
 '$35 USD per hour',
 '$15 USD per hour',
 '$20 USD per hour',
 '$50 USD per hour',
 '$20 USD per hour',
 '$30 USD per hour']

In [384]:
profile0=doc.find_all(class_="bio truncProfile")
profile0

[<div class="bio truncProfile"><span class="profile_text">Experienced Full Stack Developer with expertise in web and mobile application development, blockchain solutions, and AI integrations. Proficient in React, Next.js, Node.js, and React Native, I specialize in building scalable, high-performance applications. Skilled in backend technologies like Express.js, NestJS, and...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">♻️ Looking to enhance your business productivity through automation?
 ♻️ Struggling with redundant tasks that eat up your time and resources?

 ? Let's redefine efficiency with smart, automated systems that give you back the most valuable resource—time.

 ? I specialize in using advanced automation platforms to...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Hi there,

 My name is Gulzar, and I am a professional Computer Systems Engineer with passion as well as dedication towards
 Python, WordPress, PHP, React, Java, Technical and Customer Support, 3D Modeling, Video Editing, and Content Writing, and have a keen interest in adopting new technologies to be market competitive...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I am a highly skilled Full Stack Developer with expertise in MERN Stack, PHP, WordPress, Automation, Web Scraping, and Shopify Development.
 With years of experience, I specialize in building scalable, high-performance web applications and automation solutions that drive efficiency and business growth.

 ⚡ Core Skills...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">I am an engineer with more than ten years of experience. I am a skilled programmer in Python, C++, Java,VBA, and Fortran.I am an expert in 3d modeling. I am skilled in using Autocad, Revit,3DsMAX, Solidworks, Inventor, CATIA, and Blender. I can also simulate and perform stress analysis of different objects from...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">Dynamic and experienced Senior Full Stack Developer with over 8 years of expertise in building robust web applications and services. Proficient in a wide range of technologies including JavaScript, PHP, Ruby on Rails, and Python, with a strong background in both front-end and back-end development.

 Specialized in AI...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">A dedicated developer with a passion for crafting clean and efficient code. Committed to excellence in every project, I deliver results that speak for themselves. I have over 10+ years of experience. I strive to satisfy customers and make them happy. The single most important thing for me is to deliver "Quality...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>,
 <div class="bio truncProfile"><span class="profile_text">More than 10 years of experience in designing, user-centered meaningful and functional UI and UX and transforming it to life across the web and mobile platform.

 AREAS OF EXPERTISE:

 Design:

 • UX Research
 • Planning
 • Low Fidelity Design
 • High Fidelity Design
 • Testing
 • User Interface (UI) Design
 • Web...</span> <a class="seeMore" data-action="more" style="display:none">more</a></div>]

In [386]:
for p in profile0:
    print(p.text)

Experienced Full Stack Developer with expertise in web and mobile application development, blockchain solutions, and AI integrations. Proficient in React, Next.js, Node.js, and React Native, I specialize in building scalable, high-performance applications. Skilled in backend technologies like Express.js, NestJS, and... more
♻️ Looking to enhance your business productivity through automation?
♻️ Struggling with redundant tasks that eat up your time and resources?

? Let's redefine efficiency with smart, automated systems that give you back the most valuable resource—time.

? I specialize in using advanced automation platforms to... more
Hi there,

My name is Gulzar, and I am a professional Computer Systems Engineer with passion as well as dedication towards
Python, WordPress, PHP, React, Java, Technical and Customer Support, 3D Modeling, Video Editing, and Content Writing, and have a keen interest in adopting new technologies to be market competitive... more
I am a highly skilled Full Stack Developer with expertise in MERN Stack, PHP, WordPress, Automation, Web Scraping, and Shopify Development.
With years of experience, I specialize in building scalable, high-performance web applications and automation solutions that drive efficiency and business growth.

⚡ Core Skills... more
I am an engineer with more than ten years of experience. I am a skilled programmer in Python, C++, Java,VBA, and Fortran.I am an expert in 3d modeling. I am skilled in using Autocad, Revit,3DsMAX, Solidworks, Inventor, CATIA, and Blender. I can also simulate and perform stress analysis of different objects from... more
Dynamic and experienced Senior Full Stack Developer with over 8 years of expertise in building robust web applications and services. Proficient in a wide range of technologies including JavaScript, PHP, Ruby on Rails, and Python, with a strong background in both front-end and back-end development.

Specialized in AI... more
A dedicated developer with a passion for crafting clean and efficient code. Committed to excellence in every project, I deliver results that speak for themselves. I have over 10+ years of experience. I strive to satisfy customers and make them happy. The single most important thing for me is to deliver "Quality... more
More than 10 years of experience in designing, user-centered meaningful and functional UI and UX and transforming it to life across the web and mobile platform.

AREAS OF EXPERTISE:

Design:

• UX Research
• Planning
• Low Fidelity Design
• High Fidelity Design
• Testing
• User Interface (UI) Design
• Web... more

In [388]:
profile3 = [p.text for p in profile0]
profile3

['Experienced Full Stack Developer with expertise in web and mobile application development, blockchain solutions, and AI integrations. Proficient in React, Next.js, Node.js, and React Native, I specialize in building scalable, high-performance applications. Skilled in backend technologies like Express.js, NestJS, and... more',
 "♻️ Looking to enhance your business productivity through automation?\n♻️ Struggling with redundant tasks that eat up your time and resources?\n\n? Let's redefine efficiency with smart, automated systems that give you back the most valuable resource—time.\n\n? I specialize in using advanced automation platforms to... more",
 'Hi there,\n\nMy name is Gulzar, and I am a professional Computer Systems Engineer with passion as well as dedication towards\nPython, WordPress, PHP, React, Java, Technical and Customer Support, 3D Modeling, Video Editing, and Content Writing, and have a keen interest in adopting new technologies to be market competitive... more',
 'I am a highly skilled Full Stack Developer with expertise in MERN Stack, PHP, WordPress, Automation, Web Scraping, and Shopify Development. \nWith years of experience, I specialize in building scalable, high-performance web applications and automation solutions that drive efficiency and business growth.\n\n⚡ Core Skills... more',
 'I am an engineer with more than ten years of experience. I am a skilled programmer in Python, C++, Java,VBA, and Fortran.I am an expert in 3d modeling. I am skilled in using Autocad, Revit,3DsMAX, Solidworks, Inventor, CATIA, and Blender. I can also simulate and perform stress analysis of different objects from... more',
 'Dynamic and experienced Senior Full Stack Developer with over 8 years of expertise in building robust web applications and services. Proficient in a wide range of technologies including JavaScript, PHP, Ruby on Rails, and Python, with a strong background in both front-end and back-end development.\n\nSpecialized in AI... more',
 'A dedicated developer with a passion for crafting clean and efficient code. Committed to excellence in every project, I deliver results that speak for themselves. I have over 10+ years of experience. I strive to satisfy customers and make them happy. The single most important thing for me is to deliver "Quality... more',
 'More than 10 years of experience in designing, user-centered meaningful and functional UI and UX and transforming it to life across the web and mobile platform. \n\nAREAS OF EXPERTISE: \n\nDesign:\n\n• UX Research \n• Planning \n• Low Fidelity Design \n• High Fidelity Design\n• Testing \n• User Interface (UI) Design \n• Web... more']

In [390]:
table3=pd.DataFrame({"Name": name1, "Review score": review1, "Earning": earning1, "# of reviews": number1, "Rate": rate1, "Profile": profile1})
table3

,Name,Review score,Earning,# of reviews,Rate,Profile
0,WebDevWang,4.8,3.8,4 reviews,$50 USD per hour,⚡️ With 5 years of experience as a Full Stack ...
1,tangramua,4.0,7.2,38 reviews,$35 USD per hour,We are Canadian-Ukrainian team of highly profe...
2,mixun0,5.0,3.2,3 reviews,$70 USD per hour,I have experience in building websites and mob...
3,pauldinhdev,5.0,4.4,6 reviews,$70 USD per hour,With over 10 years of experience in the IT ind...
4,amirrmusavifr,4.8,4.8,12 reviews,$20 USD per hour,"I have master in Electrical Engineering, I'm e..."
5,alextoross09,5.0,4.1,16 reviews,$40 USD per hour,I am a highly skilled Data Scientist and Softw...
6,Tereus77,5.0,2.5,1 review,$35 USD per hour,My name is William and I am an experienced AI ...
7,anisbouk,5.0,1.8,2 reviews,$40 USD per hour,I am a Senior Software Engineer with over 10 y...
8,PentabayC,5.0,1.8,2 reviews,$35 USD per hour,Most Reviewed Companies by The Manifest in the...
9,jameso64,0.0,0.0,0 reviews,$20 USD per hour,As a verified top-rated Upwork Full-Stack Solu...

In [392]:
freelance_table = pd.concat([table1, table2, table3], ignore_index=True)
freelance_table

,Name,Review score,Earning,# of reviews,Rate,Profile
0,WebDevWang,4.8,3.8,4 reviews,$50 USD per hour,⚡️ With 5 years of experience as a Full Stack ...
1,tangramua,4.0,7.2,38 reviews,$35 USD per hour,We are Canadian-Ukrainian team of highly profe...
2,mixun0,5.0,3.2,3 reviews,$70 USD per hour,I have experience in building websites and mob...
3,pauldinhdev,5.0,4.4,6 reviews,$70 USD per hour,With over 10 years of experience in the IT ind...
4,amirrmusavifr,4.8,4.8,12 reviews,$20 USD per hour,"I have master in Electrical Engineering, I'm e..."
5,alextoross09,5.0,4.1,16 reviews,$40 USD per hour,I am a highly skilled Data Scientist and Softw...
6,Tereus77,5.0,2.5,1 review,$35 USD per hour,My name is William and I am an experienced AI ...
7,anisbouk,5.0,1.8,2 reviews,$40 USD per hour,I am a Senior Software Engineer with over 10 y...
8,PentabayC,5.0,1.8,2 reviews,$35 USD per hour,Most Reviewed Companies by The Manifest in the...
9,jameso64,0.0,0.0,0 reviews,$20 USD per hour,As a verified top-rated Upwork Full-Stack Solu...
10,Time2Sync,0.0,0.0,0 reviews,$30 USD per hour,"Welcome to Time2sync, your go-to partner for i..."
11,tonyc00,0.0,0.0,0 reviews,$50 USD per hour,"Hi, I’m a Data Scientist and AI/ML Engineer wi..."
12,jameso64,0.0,0.0,0 reviews,$20 USD per hour,As a verified top-rated Upwork Full-Stack Solu...
13,juliann36,0.0,0.0,0 reviews,$15 USD per hour,With over 6 years of experience in full-stack ...
14,dilshodd1,0.0,0.0,0 reviews,$40 USD per hour,"Hello! My name is Dilshod, and I specialize in..."
15,daniell162,0.0,0.0,0 reviews,$15 USD per hour,I am a highly skilled Full-Stack Developer wit...
16,markw096,0.0,0.0,0 reviews,$20 USD per hour,Hello! I am a dedicated AI and Image Processin...
17,martinm034,0.0,0.0,0 reviews,$20 USD per hour,As a skilled Full-Stack Developer with a deep ...
18,nuhumalik,0.0,0.0,0 reviews,$40 USD per hour,Hello.\n\nThis is a versatile fullstack develo...
19,jamess219,0.0,0.0,0 reviews,$30 USD per hour,I am a Sr. full stack developer with extensive...
20,WebDevWang,4.8,3.8,4 reviews,$50 USD per hour,⚡️ With 5 years of experience as a Full Stack ...
21,tangramua,4.0,7.2,38 reviews,$35 USD per hour,We are Canadian-Ukrainian team of highly profe...
22,mixun0,5.0,3.2,3 reviews,$70 USD per hour,I have experience in building websites and mob...
23,pauldinhdev,5.0,4.4,6 reviews,$70 USD per hour,With over 10 years of experience in the IT ind...
24,amirrmusavifr,4.8,4.8,12 reviews,$20 USD per hour,"I have master in Electrical Engineering, I'm e..."
25,alextoross09,5.0,4.1,16 reviews,$40 USD per hour,I am a highly skilled Data Scientist and Softw...
26,Tereus77,5.0,2.5,1 review,$35 USD per hour,My name is William and I am an experienced AI ...
27,anisbouk,5.0,1.8,2 reviews,$40 USD per hour,I am a Senior Software Engineer with over 10 y...
28,PentabayC,5.0,1.8,2 reviews,$35 USD per hour,Most Reviewed Companies by The Manifest in the...
29,jameso64,0.0,0.0,0 reviews,$20 USD per hour,As a verified top-rated Upwork Full-Stack Solu...

In [394]:
freelance_table.to_excel("freelancedata.xlsx")